### Signup

POST http://localhost:9000/api/auth/signup 
Content-Type: application/json

{
  "username" : "amithbuy", 
  "password" : "12345678",
  "type" : "buyer"
}

### Login

POST http://localhost:9000/api/auth/login 
Content-Type: application/json

{
  "username" : "amith", 
  "password" : "12345678"
}

### me

GET http://localhost:9000/api/auth/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXRoMSIsImlhdCI6MTY5MTA0Nzk5OX0.kE6xPkynjIyawJgXvox4hEF8Q3pJM9_wunJaWDDsLgA

### create procuct

POST http://localhost:9000/api/app/createproduct
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXRoMSIsImlhdCI6MTY5MTA0Nzk5OX0.kE6xPkynjIyawJgXvox4hEF8Q3pJM9_wunJaWDDsLgA

{
  "username" : "amith1",
  "title" : "Title of product",
  "description" : "this is a very nice produce",
  "price" : 200,
  "options" : ["Emi Availble", "Returnable"],
  "info" : "This is a really long description of the product",
  "img1": "some img string",
  "img2": "some img string",
  "img3": "some img string",
  "img4": "some img string"
}

### Get products

GET http://localhost:9000/api/app/getproducts

### Get product

GET http://localhost:9000/api/app/getproduct/64cc7cfd8a5d0b12f56d3823

### buy

POST http://localhost:9000/api/app/buyproduct
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXRoYnV5IiwiaWF0IjoxNjkxMjQ5NjA0fQ.UafsCe8oK3xUKEZTp3Jk1vb30EBaXlnb5wsxYNwZLT4

{
  "seller" : "amith",
  "pid" : "dlfksdksfdfddk"
}

### get orders

GET http://localhost:9000/api/app/seller/getorder
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXRoMSIsImlhdCI6MTY5MTI0OTI4Mn0.pwuPWMOqXi-FMvfOY0_ou19FBlUFeuXHHEoujkW737w

### get orders

GET http://localhost:9000/api/app/buyer/getorder
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXRoYnV5IiwiaWF0IjoxNjkxMjQ5NjA0fQ.UafsCe8oK3xUKEZTp3Jk1vb30EBaXlnb5wsxYNwZLT4

### add to cart

POST http://localhost:9000/api/app/addtocart
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXRoYnV5IiwiaWF0IjoxNjkxMjQ5NjA0fQ.UafsCe8oK3xUKEZTp3Jk1vb30EBaXlnb5wsxYNwZLT4

{
  "pid" : "43l3k42335435k43"
}

### get cart

GET http://localhost:9000/api/app/getcart
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXRoYnV5IiwiaWF0IjoxNjkxMjQ5NjA0fQ.UafsCe8oK3xUKEZTp3Jk1vb30EBaXlnb5wsxYNwZLT4


### buy from cart

POST http://localhost:9000/api/app/buyfromcart
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXRoYnV5IiwiaWF0IjoxNjkxMjQ5NjA0fQ.UafsCe8oK3xUKEZTp3Jk1vb30EBaXlnb5wsxYNwZLT4

{
  "pid" : ["lkdf", "dsfdf"],
  "seller": ["somerandome", "someone"]
}